version: '3.8'

services:
  api:
    container_name: api
    build: 
      context: .
    environment:
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - /app/node_modules
    depends_on:
      - postgres
    #command: npm run dev 


  postgres:
    container_name: db
    image: postgres:13
    environment:
     - POSTGRES_DB=db_docker
     - POSTGRES_USER=gabriel
     - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    # volumes:
    #   - ./postgres_data:/var/lib/postgresql/data
      